name: Bug Report
description: File a bug report to help us improve UltraKOTHPlusPlus
title: "[BUG] "
labels: ["bug", "triage"]
assignees: ["sansnom"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of UltraKOTHPlusPlus are you running?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: Server Software & Version
      description: What server software and version are you using?
      placeholder: e.g., Paper 1.19.4-545
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: What version of Java is your server running?
      placeholder: e.g., Java 17.0.6

  - type: textarea
    id: plugins
    attributes:
      label: Other Plugins
      description: List other plugins that might be related to this issue
      placeholder: |
        - WorldGuard 7.0.9
        - PlaceholderAPI 2.11.5
        - etc.

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Error Messages
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
